version: '3.7'
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 main:app
    volumes:
      - ./app/:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
