version: '3.7'
services:
  web:
    build: .
    command:  python /app/tests/testget.py 
    volumes:
      - ./app/:/app/
    ports:
      - 9090:80
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgres_data:
