name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image 
      run: docker build -t flask_image .
    - name: Run application container
      run: docker run --rm -d --name flask-container -p 80:80 flask_image
    - name: Run tests in the container 
      run: |
        curl http://localhost:80/hello/ || true
        python app/tests/testget.py || true
        echo "APP is working"
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nsvijay04b1/flask_image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true  
     
        
        
