name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image 
      run: docker build -t flask_image .
    - name: Run application container
      run: docker-compose -f  docker-compose-dev.yaml up -d --build
    - name: Run tests in the container 
      run: |
        docker-compose -f  docker-compose-dev.yaml ps || true
        sleep 30
        docker exec -it hello-restapi_web_1 python /app/tests/testget.py || true
        curl -X GET 'http://localhost:8080/hello/TestLeap' || true
        docker-compose -f  docker-compose-dev.yaml ps || true
        echo "APP is working"
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nsvijay04b1/flask_image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true  
     
        
        
