name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image 
      run: docker build -t flask_image .
    - name: Run application container
      run: docker run --rm -d --name flask-container -p 80:80 flask_image
    - name: Run tests in the container and push the docker image to github
      run: |
        curl localhost/hello/
        python app/tests/testget.py
        docker tag flask_image docker.io/nsvijay04b1/flask_image
        docker push docker.io/nsvijay04b1/flask_image
        echo "CI passed"
        
        
